name: music_kit_darwin
description: "Apple (ios and macos) implementation of music_kit"
version: 1.3.0
homepage: https://github.com/misiio/flutter_music_kit/tree/master/packages/music_kit_darwin

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: MusicKitPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: MusicKitPlugin
        sharedDarwinSource: true

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
