name: music_kit_platform_interface
description: A common platform interface for the music_kit plugin.
version: 1.2.0
homepage: https://github.com/misiio/flutter_music_kit/tree/master/music_kit_platform_interface

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  plugin_platform_interface: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.2

flutter:
